# Generated by Django 5.0.3 on 2024-07-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_alter_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about_me',
        ),
    ]
