# Generated by Django 5.0.3 on 2024-06-30 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0001_initial'),
        ('product', '0003_productcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='سایز'),
        ),
    ]
