# Generated by Django 5.0.3 on 2024-06-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0002_orderingitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
