# Generated by Django 5.0.3 on 2024-07-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0003_alter_ordering_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی سبد خرید'),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
