# Generated by Django 5.0.3 on 2024-07-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0004_ordering_final_price_alter_ordering_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='final_price',
        ),
    ]
