# Generated by Django 5.0.3 on 2024-07-09 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0005_remove_ordering_final_price'),
        ('Rent', '0004_remove_rentday_product_rent_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingitem',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rent.rentday', verbose_name='روز'),
        ),
    ]
