# Generated by Django 5.0.3 on 2024-07-09 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0006_orderingitem_day'),
        ('Rent', '0004_remove_rentday_product_rent_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderingRentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی')),
                ('total_quantity', models.IntegerField(verbose_name='تعداد')),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rent.rentday', verbose_name='روز')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ordering.ordering', verbose_name='سبد خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent.rent', verbose_name='محصول')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rent.rentsize', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'جزئیات خرید',
                'verbose_name_plural': 'جزئیات خریدها',
            },
        ),
    ]
