# Generated by Django 5.0.3 on 2024-07-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0007_orderingrentitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderingitem',
            name='day',
        ),
    ]
