# Generated by Django 5.0.3 on 2024-07-09 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0002_rentsize_gallery_rentcategory_alter_rent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent.rent', verbose_name='محصول'),
        ),
        migrations.CreateModel(
            name='RentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='بازه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent.rent', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'بازه',
                'verbose_name_plural': 'بازه ها',
            },
        ),
    ]
