# Generated by Django 5.0.3 on 2024-07-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0003_alter_rentcomment_product_rentday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentday',
            name='product',
        ),
        migrations.AddField(
            model_name='rent',
            name='day',
            field=models.ManyToManyField(to='Rent.rentday', verbose_name='بازه'),
        ),
    ]
