# Generated by Django 5.0.3 on 2024-04-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0003_profileimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimages',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
