# Generated by Django 5.0.3 on 2024-05-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('domain', models.CharField(max_length=100, verbose_name='دامنه سایت')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(verbose_name='ادرس')),
                ('about_us', models.TextField(verbose_name='توضیح')),
                ('copyright', models.TextField(verbose_name='حق کپی رایت')),
                ('logo', models.ImageField(upload_to='images/logo/', verbose_name='لوگو')),
                ('is_main_settings', models.BooleanField(default=True, verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
