# Generated by Django 5.0.3 on 2024-05-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_settings', '0002_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='links',
            field=models.URLField(blank=True, null=True, verbose_name='لینک'),
        ),
    ]
