# Generated by Django 5.0.3 on 2024-06-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_settings', '0003_alter_footerlink_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url_title', models.URLField(blank=True, null=True, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'بنر سایت',
                'verbose_name_plural': 'بنرهای سایت',
            },
        ),
    ]
