# Generated by Django 5.0.3 on 2024-07-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_settings', '0006_footerlink_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='value',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='مقدار'),
        ),
    ]
