# Generated by Django 5.0.3 on 2024-07-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_settings', '0007_alter_footerlink_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlink',
            name='value',
        ),
        migrations.AddField(
            model_name='footerlink',
            name='instagram',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='mobile',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='موبایل'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='telegram',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='تلگرام'),
        ),
    ]
