# Generated by Django 5.0.3 on 2024-07-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_settings', '0008_remove_footerlink_value_footerlink_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instagram',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='تلگرام'),
        ),
    ]
