# Generated by Django 5.0.3 on 2024-07-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_settings', '0010_remove_footerlink_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlink',
            name='mobile',
        ),
        migrations.AddField(
            model_name='footerlink',
            name='value',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='مقدار'),
        ),
    ]
