# Generated by Django 5.0.3 on 2024-07-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_settings', '0011_remove_footerlink_mobile_footerlink_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مقدار'),
        ),
    ]
