# Generated by Django 5.0.3 on 2024-05-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/sliders/', verbose_name='عکس'),
        ),
    ]
